import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import LocationForm from 'src/pages/components/LocationForm'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Rent My Tools</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className=
          "bg-white dark:bg-slate-800 rounded-lg px-6 py-8 ring-1 ring-slate-900 shadow-xl text-center">
        <div>
        </div>
        <h3
          className=
            "text-slate-700 dark:text-white mt-5 text-base font-medium tracking-tight text-3xl">
            Rent My Tools</h3>
            <p className="text-slate-500 dark:text-slate-400 mt-2 text-sm">
            Tool Rental App
          </p>
      </div>
      <div>
        <LocationForm />
      </div>
    </>
  )
}
